import type { ThemeDefinition, WeekStartOption } from "@/types";

export const RESOLUTIONS = {
  desktop: { width: 3840, height: 2160, label: "Desktop" },
  mobile: { width: 1080, height: 1920, label: "Mobile" },
} as const;

export const LOCALES = [
  { code: "en-US", label: "United States" },
  { code: "ja-JP", label: "Japan" },
  { code: "zh-TW", label: "Taiwan" },
  { code: "zh-CN", label: "China" },
  { code: "ko-KR", label: "South Korea" },
  { code: "es-ES", label: "Spain" },
  { code: "fr-FR", label: "France" },
  { code: "de-DE", label: "Germany" },
];

export const THEMES: ThemeDefinition[] = [
  {
    id: "bubble-dream",
    name: "Bubble Dream",
    description: "Holo gradients, dreamy bubbles.",
    bgClass: "bg-white",
    textClass: "text-[#4c1d95]",
    accentClass: "bg-[#e879f9]",
    defaultAccent: "#a855f7",
    fontHeading: "font-bouncy",
    fontBody: "font-cute",
    headerAlign: "center",
    dateLayout: "circle-floating",
    dateAlign: "center",
    weekendStyle: "highlight",
    cardStyle: "glass",
    decorator: "bubble-gradient",
  },
  {
    id: "serene-sky",
    name: "Serene Sky",
    description: "Crisp monochrome with airy blue highlights.",
    bgClass: "bg-gradient-to-br from-[#C6E7FF] via-[#D4F6FF] to-[#FBFBFB]",
    textClass: "text-[#0f172a]",
    accentClass: "bg-[#7ac7ff]",
    defaultAccent: "#7ac7ff",
    fontHeading: "font-clean",
    fontBody: "font-sans",
    headerAlign: "center",
    dateLayout: "inline",
    dateAlign: "center",
    weekendStyle: "soft-bg",
    cardStyle: "soft-shadow",
    decorator: "soft-gradient",
  },
  {
    id: "pop-art",
    name: "Pop Art",
    description: "Bold comic style, halftone dots.",
    bgClass: "bg-[#fef08a]",
    textClass: "text-black",
    accentClass: "bg-[#ef4444]",
    defaultAccent: "#000000",
    fontHeading: "font-bouncy",
    fontBody: "font-clean",
    headerAlign: "left",
    dateLayout: "comic-box",
    dateAlign: "left",
    weekendStyle: "dot-indicator",
    cardStyle: "comic",
    decorator: "halftone",
  },
  {
    id: "scrapbook-memory",
    name: "Scrapbook",
    description: "Textured paper, polaroid feel.",
    bgClass: "bg-[#e7e5e4]",
    textClass: "text-[#44403c]",
    accentClass: "bg-[#d6d3d1]",
    defaultAccent: "#78716c",
    fontHeading: "font-hand",
    fontBody: "font-journal",
    headerAlign: "center",
    dateLayout: "stacked",
    dateAlign: "center",
    weekendStyle: "soft-bg",
    cardStyle: "polaroid",
    decorator: "paper-texture",
  },
  {
    id: "retro-vapor",
    name: "Vaporwave 95",
    description: "Soft palms, neon haze, and dreamy gradients.",
    bgClass:
      "bg-gradient-to-br from-[#0f172a] via-[#4338ca] to-[#f472b6] text-[1px]",
    textClass: "text-[#f8fafc] shadow-[0_0_12px_rgba(248,250,252,0.8)]",
    accentClass: "bg-gradient-to-r from-[#22d3ee] to-[#f472b6]",
    defaultAccent: "#22d3ee",
    fontHeading: "font-tech",
    fontBody: "font-clean",
    headerAlign: "center",
    dateLayout: "circle-floating",
    dateAlign: "center",
    weekendStyle: "soft-bg",
    cardStyle: "neon",
    decorator: "neon-grid",
  },
  {
    id: "cyber-glitch",
    name: "Cyber Glitch",
    description: "Glitchy terminals, electric green pulses.",
    bgClass: "bg-[#01040c]",
    textClass: "text-[#68f8e5]",
    accentClass: "bg-gradient-to-r from-[#22c55e] to-[#4ade80]",
    defaultAccent: "#34d399",
    fontHeading: "font-mono",
    fontBody: "font-tech",
    headerAlign: "left",
    dateLayout: "minimal-corner",
    dateAlign: "left",
    weekendStyle: "tint-text",
    cardStyle: "outline",
    decorator: "scanlines",
  },
  {
    id: "vintage-news",
    name: "Vintage Press",
    description: "Old newspaper, classic serif.",
    bgClass: "bg-[#f5f5dc]",
    textClass: "text-[#292524]",
    accentClass: "bg-[#57534e]",
    defaultAccent: "#292524",
    fontHeading: "font-serif",
    fontBody: "font-journal",
    headerAlign: "center",
    dateLayout: "big-left",
    dateAlign: "center",
    weekendStyle: "default",
    cardStyle: "outline",
    decorator: "paper-texture",
  },
  {
    id: "bauhaus-mod",
    name: "Bauhaus",
    description: "Geometric, primary colors.",
    bgClass: "bg-[#f4f4f5]",
    textClass: "text-[#18181b]",
    accentClass: "bg-[#ef4444]",
    defaultAccent: "#2563eb",
    fontHeading: "font-tech",
    fontBody: "font-clean",
    headerAlign: "left",
    dateLayout: "stacked",
    dateAlign: "left",
    weekendStyle: "default",
    cardStyle: "bauhaus-block",
    decorator: "geometric-shapes",
  },
  {
    id: "botanical-art",
    name: "Botanical",
    description: "Natural textures, organic feel.",
    bgClass: "bg-[#f0fdf4]",
    textClass: "text-[#14532d]",
    accentClass: "bg-[#86efac]",
    defaultAccent: "#15803d",
    fontHeading: "font-organic",
    fontBody: "font-journal",
    headerAlign: "center",
    dateLayout: "stacked",
    dateAlign: "center",
    weekendStyle: "soft-bg",
    cardStyle: "outline",
    decorator: "ivy-leaves",
  },
  {
    id: "lux-gold",
    name: "Royal Luxe",
    description: "Black & Gold, premium.",
    bgClass: "bg-[#1c1917]",
    textClass: "text-[#f5f5f4]",
    accentClass: "bg-[#ca8a04]",
    defaultAccent: "#eab308",
    fontHeading: "font-luxury",
    fontBody: "font-editorial",
    headerAlign: "center",
    dateLayout: "inline",
    dateAlign: "center",
    weekendStyle: "dot-indicator",
    cardStyle: "outline",
    decorator: "lux-frame",
  },
  {
    id: "pastel-diary",
    name: "Pastel Diary",
    description: "Soft, rounded, like a paper planner.",
    bgClass: "bg-[#fffbf0]",
    textClass: "text-[#5c5c5c]",
    accentClass: "bg-[#ffb7b2]",
    defaultAccent: "#e17070",
    fontHeading: "font-hand",
    fontBody: "font-cute",
    headerAlign: "center",
    dateLayout: "stacked",
    dateAlign: "center",
    weekendStyle: "soft-bg",
    cardStyle: "soft-shadow",
    decorator: "dots",
  },
  {
    id: "sakura-breeze",
    name: "Sakura Breeze",
    description: "Delicate pinks, serif fonts, airy feel.",
    bgClass: "bg-[#fff0f5]",
    textClass: "text-[#883a47]",
    accentClass: "bg-[#ffa6c1]",
    defaultAccent: "#be185d",
    fontHeading: "font-organic",
    fontBody: "font-sans",
    headerAlign: "center",
    dateLayout: "badge-top",
    dateAlign: "center",
    weekendStyle: "highlight",
    cardStyle: "glass",
    decorator: "soft-gradient",
    customCSS: {
      backgroundImage:
        "linear-gradient(135deg, #fff0f5 0%, #fff5f7 50%, #ffeef2 100%)",
    },
  },
  {
    id: "cozy-mocha",
    name: "Cozy Mocha",
    description: "Latte tones, bold serif numbers.",
    bgClass: "bg-[#fdfcf8]",
    textClass: "text-[#4a3b32]",
    accentClass: "bg-[#a68b7c]",
    defaultAccent: "#78350f",
    fontHeading: "font-journal",
    fontBody: "font-journal",
    headerAlign: "left",
    dateLayout: "big-left",
    dateAlign: "left",
    weekendStyle: "tint-text",
    cardStyle: "marker",
    decorator: "noise",
  },
  {
    id: "kawaii-notes",
    name: "Kawaii Pop",
    description: "Super cute, doodles, pastel fun.",
    bgClass: "bg-[#fff5f7]",
    textClass: "text-[#831843]",
    accentClass: "bg-[#fb7185]",
    defaultAccent: "#ff6b6b",
    fontHeading: "font-bouncy",
    fontBody: "font-rounded",
    headerAlign: "center",
    dateLayout: "circle-floating",
    dateAlign: "center",
    weekendStyle: "highlight",
    cardStyle: "sticker",
    decorator: "doodles",
  },
  {
    id: "editorial-chic",
    name: "Editorial",
    description: "Bold typography, black & white.",
    bgClass: "bg-white",
    textClass: "text-black",
    accentClass: "bg-black",
    defaultAccent: "#111827",
    fontHeading: "font-editorial",
    fontBody: "font-sans",
    headerAlign: "left",
    dateLayout: "background-ghost",
    dateAlign: "left",
    weekendStyle: "default",
    cardStyle: "outline",
    decorator: "none",
  },
  {
    id: "clean-nude",
    name: "Nude Essentials",
    description: "Beige aesthetic, clean lines.",
    bgClass: "bg-[#f5f5f0]",
    textClass: "text-[#59544d]",
    accentClass: "bg-[#a89f91]",
    defaultAccent: "#57534e",
    fontHeading: "font-clean",
    fontBody: "font-clean",
    headerAlign: "left",
    dateLayout: "inline",
    dateAlign: "left",
    weekendStyle: "default",
    cardStyle: "solid",
    decorator: "none",
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Pure black-and-white clarity.",
    bgClass: "bg-white",
    textClass: "text-black",
    accentClass: "bg-black",
    defaultAccent: "#000000",
    fontHeading: "font-tech",
    fontBody: "font-clean",
    headerAlign: "left",
    dateLayout: "minimal-corner",
    dateAlign: "left",
    weekendStyle: "soft-bg",
    cardStyle: "solid",
  },
  {
    id: "midnight-whisper",
    name: "Midnight",
    description: "Dark slate, glowing accents.",
    bgClass: "bg-[#0f172a]",
    textClass: "text-[#e2e8f0]",
    accentClass: "bg-[#6366f1]",
    defaultAccent: "#a5b4fc",
    fontHeading: "font-luxury",
    fontBody: "font-clean",
    headerAlign: "center",
    dateLayout: "inline",
    dateAlign: "center",
    weekendStyle: "default",
    cardStyle: "glass",
    decorator: "gradient-blobs",
  },
  {
    id: "macaron-pop",
    name: "Macaron Pop",
    description: "Sweet candy colors & gradients.",
    bgClass: "bg-[#FDEDED]",
    textClass: "text-[#F875AA]",
    accentClass: "bg-[#AEDEFC]",
    defaultAccent: "#F875AA",
    fontHeading: "font-bouncy",
    fontBody: "font-rounded",
    headerAlign: "center",
    dateLayout: "circle-floating",
    dateAlign: "center",
    weekendStyle: "highlight",
    cardStyle: "sticker",
    decorator: "none",
    customCSS: {
      backgroundImage:
        "linear-gradient(135deg, #FDEDED 0%, #EDFFF0 50%, #AEDEFC 100%)",
    },
  },
];

export const MOCK_ICS_DATA = `BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
SUMMARY:Pilates
DTSTART:20241025T090000
DTEND:20241025T100000
DESCRIPTION:Morning stretch
LOCATION:Studio A
END:VEVENT
BEGIN:VEVENT
SUMMARY:Brunch w/ Girls
DTSTART:20241025T113000
DTEND:20241025T133000
LOCATION:The Little Cafe
END:VEVENT
BEGIN:VEVENT
SUMMARY:Read
DTSTART:20241026T150000
DTEND:20241026T170000
END:VEVENT
BEGIN:VEVENT
SUMMARY:Date Night
DTSTART:20241027T190000
DTEND:20241027T213000
LOCATION:Downtown
END:VEVENT
END:VCALENDAR`;

export const ACCENT_COLORS = [
  "#ffffff",
  "#18181b",
  "#ef4444",
  "#f97316",
  "#84cc16",
  "#06b6d4",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
] as const;

export const VIEW_MODES = ["month", "week", "2-week"] as const;

export const WEEK_START_OPTIONS: { value: WeekStartOption; label: string }[] = [
  { value: "sunday", label: "Sunday" },
  { value: "monday", label: "Monday" },
];

export const MONTHS = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] as const;
